import React, { useEffect, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { ArrowUpRight, ArrowRight, Play, X, Menu, Layers3, Smartphone, PenTool, ChartNoAxesCombined, ShieldCheck, Box, Cross, Mail, Phone, MapPin, Plus, Minus, MoveUpRight, Instagram, Linkedin } from 'lucide-react';
import { AnimatePresence, motion } from 'framer-motion';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import { useStudioMotion, useReducedMotionPreference } from './useStudioMotion';
import './style.css';
const photos = {office:'/images/office.webp',fashion:'/images/fashion.webp',cafe:'/images/cafe.webp',architecture:'/images/architecture.webp',health:'/images/health.webp',desk:'/images/desk.webp'};
const services = [
 {title:'Web Development', icon:Layers3,copy:'Fast, thoughtful websites. Built to turn visitors into customers.',details:'Business websites, custom web applications, e-commerce, and performance optimization. Built for your customers and easy for your team to maintain.'},
 {title:'App Development',icon:Smartphone,copy:'Big ideas. Intuitive apps. Right in the palm of your hand.',details:'Mobile experiences for iOS and Android, from product discovery and prototypes to development, launch, and ongoing improvements.'},
 {title:'UI/UX Design',icon:PenTool,copy:'Experiences that feel right. And work even better.',details:'User research, interface design, interactive prototypes, and design systems. We make complex products simple to understand and a pleasure to use.'},
 {title:'Digital Marketing',icon:ChartNoAxesCombined,copy:'Get discovered. Build connections. Make growth happen.',details:'Search optimization, paid campaigns, landing pages, analytics, and conversion improvements. A connected approach to reaching the right audience.'},
 {title:'Maintenance & Support',icon:ShieldCheck,copy:'Behind the scenes. Ahead of the problems.',details:'Ongoing technical care, updates, monitoring, security checks, and improvements that keep your digital presence dependable.'}
];
const projects = [
 {name:'Kyzo',category:'E-commerce',image:photos.fashion,description:'A sharper expression of everyday style.',theme:'fashion',headline:'Not just worn.\nLived in.',tags:'Brand experience / E-commerce',body:'A fashion commerce concept bringing editorial storytelling and an intuitive shopping journey together. The focus: let the collection speak, and make discovery effortless.'},
 {name:'Buy N Build',category:'Marketplace',image:photos.architecture,description:'Built for the next generation of builders.',theme:'build',headline:'Better spaces.\nStart here.',tags:'Strategy / Marketplace',body:'A marketplace concept for building materials and better spaces. Clear categories and an approachable visual language help turn an overwhelming search into a confident next step.'},
 {name:'The Slow House',category:'Hospitality',image:photos.cafe,description:'A digital home for the art of slowing down.',theme:'cafe',headline:'Good things.\nTake their time.',tags:'Art direction / Web experience',body:'A warm, immersive café concept inspired by quiet mornings and considered details. Rich photography and a simple structure put the space, the coffee, and the experience first.'},
 {name:'Shivakrupa Hospital',category:'Healthcare',image:photos.health,description:'Care begins with a better experience.',theme:'health',headline:'Expert care.\nHuman first.',tags:'UI/UX / Web development',body:'A healthcare website concept centered on clarity and reassurance. Accessible information and straightforward navigation help people find care without unnecessary friction.'}
];
const capabilities = [
 ['Engineering','Frontend Development','React','Backend Development','Node.js','APIs','PostgreSQL','Supabase','Mobile Development'],
 ['Growth','SEO','Local SEO','Google Business Profile','Meta Ads','Conversion Optimization','Sales Funnels','Analytics','Marketing Automation'],
 ['Experiences','UI/UX','Brand Identity','Motion Design','E-commerce','Shopify','Performance','Core Web Vitals','CRM Integrations'],
];
const perspectives = [
 {title:'A beautiful website',accent:'is only the beginning.',category:'Strategy',body:'Your website should do more than make a good first impression. Start by defining the action that matters: a conversation, a booking, a purchase. Then work backward. Make the journey clear, remove distractions, and measure whether people can complete it. Design earns its place when it makes the next step easier.'},
 {title:'Performance is part',accent:'of the experience.',category:'Engineering',body:'Speed changes how a website feels. Use appropriately sized images, reserve space for media, and keep the initial JavaScript small. Test on a real phone and a slower connection. The most memorable interaction is often the one that responds immediately.'},
 {title:'Good collaboration',accent:'makes better work.',category:'Studio',body:'Strong projects start with shared expectations. Agree on the problem, decide who makes decisions, and review work in small, useful increments. Direct feedback and clear priorities help everyone spend more time on the work that matters.'},
 {title:'Technology should',accent:'make business simpler.',category:'Thinking',body:'The right technology removes work from your day. Start with the process that causes friction, understand what people need, and build the simplest reliable solution. Fewer steps, clearer information, and systems that work together leave more room to focus on your business.'},
];
function CapabilitySystem(){
 const [active,setActive]=useState(0);
 return <div className="capability-system">
   <div className="capability-tabs" role="tablist" aria-label="Our capabilities" aria-orientation="vertical">
     {capabilities.map(([title],i)=><button id={`capability-tab-${i}`} key={title} role="tab" aria-selected={active===i} aria-controls={`capability-panel-${i}`} tabIndex={active===i?0:-1} onPointerEnter={e=>{if(e.pointerType==='mouse' && !e.currentTarget.parentElement?.querySelector(':focus-visible'))setActive(i)}} onFocus={()=>setActive(i)} onClick={()=>setActive(i)} onKeyDown={e=>{let next=i;if(e.key==='ArrowDown'||e.key==='ArrowRight')next=(i+1)%3;else if(e.key==='ArrowUp'||e.key==='ArrowLeft')next=(i+2)%3;else if(e.key==='Home')next=0;else if(e.key==='End')next=2;else return;e.preventDefault();document.getElementById(`capability-tab-${next}`)?.focus()}}><span>0{i+1}</span>{title}<ArrowUpRight/></button>)}
   </div>
   <div className="capability-panels">{capabilities.map(([title,...items],i)=><div key={title} id={`capability-panel-${i}`} role="tabpanel" aria-labelledby={`capability-tab-${i}`} hidden={active!==i} tabIndex={0}><div className="skill-cloud">{items.map((item,j)=><span key={item} className={j===0||j===3?'skill-major':j===1||j===5?'skill-medium':'skill-minor'} style={{animationDelay:`${j*25}ms`}}>{item}</span>)}</div><p>One connected toolkit. Built around your ambitions.</p></div>)}</div>
 </div>
}
function Brand(){return <a className="brand" href="#home" aria-label="Tanvo home"><img className="brand-mark" src="/logo.png" alt="" width={192} height={192} decoding="async"/>Tanvo</a>}
function Label({children}:{children:React.ReactNode}){return <div className="eyebrow"><span>↦</span>{children}</div>}
function RevealHeading({lines}:{lines:React.ReactNode[]}){return <h2 className="reveal-heading">{lines.map((line,i)=><span className="heading-line" key={i}><span className="heading-line-inner">{line}</span></span>)}</h2>}
function Button({children,href='#contact',secondary=false,onClick}:{children:React.ReactNode,href?:string,secondary?:boolean,onClick?:(e:React.MouseEvent)=>void}){return <a href={href} onClick={onClick} className={`button ${secondary?'secondary':''}`} onPointerMove={e=>{if(matchMedia('(pointer:fine) and (prefers-reduced-motion: no-preference)').matches){const r=e.currentTarget.getBoundingClientRect();e.currentTarget.style.transform=`translate(${(e.clientX-r.left-r.width/2)*.08}px,${(e.clientY-r.top-r.height/2)*.12}px)`}}} onPointerLeave={e=>{e.currentTarget.style.transform=''}}>{children}<ArrowUpRight size={17}/></a>}
function Sculpture(){return <div className="sculpture" aria-hidden="true"><div className="sculpture-haze"/><div className="sculpture-rotor"><div className="structure">{[0,1,2,3,4,5,6,7,8].map(i=><div key={i} className={`cube cube-${i}`}><i className="face front"/><i className="face back"/><i className="face right"/><i className="face left"/><i className="face top"/><i className="face bottom"/></div>)}</div></div></div>}
const ENQUIRY_ENDPOINT=import.meta.env.VITE_ENQUIRY_ENDPOINT as string|undefined;
const ENQUIRY_SECRET=import.meta.env.VITE_ENQUIRY_SECRET as string|undefined;
function EnquiryForm(){
 const [status,setStatus]=useState<'idle'|'sending'|'sent'|'error'>('idle');
 const [error,setError]=useState('');
 const fail=(msg:string)=>{setError(msg);setStatus('error')};
 const send=async(e:React.FormEvent<HTMLFormElement>)=>{
  e.preventDefault();
  const form=new FormData(e.currentTarget);
  if(!ENQUIRY_ENDPOINT||!ENQUIRY_SECRET){console.error('VITE_ENQUIRY_ENDPOINT / VITE_ENQUIRY_SECRET are not set');return fail('The form is not configured yet.')}
  setStatus('sending');setError('');
  try{
   const res=await fetch(ENQUIRY_ENDPOINT,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({
    secret:ENQUIRY_SECRET,
    name:form.get('name'),email:form.get('email'),phone:form.get('phone'),
    capabilities:form.getAll('capabilities').join(', '),
    message:form.get('message'),
    pageUrl:location.href,
    tv_hp:form.get('tv_hp')
   })});
   const body=await res.json() as {status?:string,message?:string};
   if(body.status==='ok')setStatus('sent');
   else fail(body.message||'The inquiry could not be recorded.');
  }catch(err){console.error(err);fail('We could not reach the server.')}
 };
 if(status==='sent')return <div className="dialog-content enquiry-done"><Label>Inquiry received</Label><h2>Thanks. We’re on it.</h2><p>Your brief is with the team. Expect a reply within one working day — usually sooner.</p><a className="text-link" href="mailto:support@tanvo.in">support@tanvo.in <ArrowUpRight size={17}/></a></div>;
 return <div className="dialog-content"><Label>Start a project</Label><h2>Tell us what<br/>you’re <em>building.</em></h2><p className="enquiry-intro">A few details is all we need. No forms-in-triplicate, no sales sequence.</p>
  <form className="enquiry-form" onSubmit={send}>
   <p className="honeypot" aria-hidden="true"><label htmlFor="eq-hp">Leave this empty</label><input id="eq-hp" name="tv_hp" tabIndex={-1} autoComplete="off"/></p>
   <div className="field"><label htmlFor="eq-name">Your name <em>*</em></label><input id="eq-name" name="name" required maxLength={200} autoComplete="name" placeholder="Ada Lovelace"/></div>
   <div className="field"><label htmlFor="eq-email">Email <em>*</em></label><input id="eq-email" name="email" type="email" required maxLength={200} autoComplete="email" placeholder="you@company.com"/></div>
   <div className="field"><label htmlFor="eq-phone">Phone</label><input id="eq-phone" name="phone" type="tel" maxLength={60} autoComplete="tel" placeholder="+91 00000 00000"/></div>
   <fieldset className="field field-wide capability-picker"><legend>What do you need?</legend><div className="chips">{services.map(s=><label key={s.title} className="chip"><input type="checkbox" name="capabilities" value={s.title}/><span>{s.title}</span></label>)}<label className="chip"><input type="checkbox" name="capabilities" value="Not sure yet"/><span>Not sure yet</span></label></div></fieldset>
   <div className="field field-wide"><label htmlFor="eq-message">About the project <em>*</em></label><textarea id="eq-message" name="message" rows={4} required maxLength={5000} placeholder="What are you making, who is it for, and when do you need it live?"/></div>
   <div className="enquiry-actions">
    <button className="button" type="submit" disabled={status==='sending'}>{status==='sending'?'Sending…':'Send inquiry'}{status!=='sending'&&<ArrowUpRight size={17}/>}</button>
    <span className="enquiry-note">We reply within one working day.</span>
   </div>
   <p aria-live="polite" className={status==='error'?'enquiry-error':'visually-hidden'}>{status==='error'?<>{error} Please try again, or email <a href="mailto:support@tanvo.in">support@tanvo.in</a> and we’ll pick it up straight away.</>:status==='sending'?'Sending your inquiry':''}</p>
  </form></div>;
}
function App(){
 const [menu,setMenu]=useState(false);const [scrolled,setScrolled]=useState(false);const [selected,setSelected]=useState<number|null>(null);const [showreel,setShowreel]=useState(false);const [service,setService]=useState<number|null>(null);const [insight,setInsight]=useState<number|null>(null);const [enquiry,setEnquiry]=useState(false);const openEnquiry=(e:React.MouseEvent)=>{e.preventDefault();setEnquiry(true)};const dialog=useRef<HTMLDialogElement>(null);const reduce=useReducedMotionPreference();
 const modal=selected!==null||showreel||insight!==null||enquiry;
 useEffect(()=>{if(modal){dialog.current?.showModal();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous;dialog.current?.close()}}},[modal]);
 const close=()=>{setSelected(null);setShowreel(false);setInsight(null);setEnquiry(false)};
 useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>30);window.addEventListener('scroll',onScroll,{passive:true});return()=>window.removeEventListener('scroll',onScroll)},[]);
 useStudioMotion(reduce);
 useEffect(()=>{if(!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';const toggle=document.querySelector<HTMLButtonElement>('.menu-toggle');const links=Array.from(document.querySelectorAll<HTMLAnchorElement>('.mobile-menu a'));links[0]?.focus();const main=document.querySelector('main');const footer=document.querySelector('footer');if(main)main.inert=true;if(footer)footer.inert=true;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(false);if(e.key==='Tab'){const first=links[0];const last=links.at(-1);if(e.shiftKey && document.activeElement===first){e.preventDefault();toggle?.focus()}else if(!e.shiftKey && document.activeElement===last){e.preventDefault();toggle?.focus()}else if(e.shiftKey && document.activeElement===toggle){e.preventDefault();last?.focus()}}};document.addEventListener('keydown',key);return()=>{document.body.style.overflow=old;document.removeEventListener('keydown',key);if(main)main.inert=false;if(footer)footer.inert=false;toggle?.focus()}},[menu]);
 return <><a className="skip" href="#main">Skip to content</a><header className={scrolled?'nav scrolled':'nav'}><div className="nav-inner"><Brand/><nav aria-label="Main navigation">{['Work','Services','Process','About','Insights'].map(x=><a key={x} href={`#${x.toLowerCase()}`}>{x}</a>)}</nav><div className="nav-cta"><Button secondary>Let’s talk</Button></div><button className="menu-toggle" aria-label={menu?'Close menu':'Open menu'} aria-expanded={menu} aria-controls="mobile-menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></div></header>
 <AnimatePresence>{menu&&<motion.nav id="mobile-menu" className="mobile-menu" aria-label="Mobile navigation" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}>{['Home','Work','Services','Process','About','Insights','Contact'].map((x,i)=><motion.a initial={{y:reduce?0:25,opacity:0}} animate={{y:0,opacity:1}} transition={{delay:reduce?0:i*.05}} href={`#${x.toLowerCase()}`} key={x} onClick={()=>setMenu(false)}>{x}<ArrowUpRight/></motion.a>)}</motion.nav>}</AnimatePresence>
 <main id="main"><section className="hero" id="home"><div className="hero-grid"><div className="hero-copy"><Label>Web development agency · Hubli–Dharwad</Label><h1>{['Ideas','Into','Impact.'].map(t=><span className="line" key={t}><span>{t}</span></span>)}</h1><p>Tanvo builds fast websites, apps and digital growth systems for ambitious businesses in Hubli–Dharwad and across Karnataka.</p><div className="hero-actions"><Button onClick={openEnquiry}>Start a Project</Button><button className="showreel" onClick={()=>setShowreel(true)}><span><Play size={13} fill="currentColor"/></span>Our studio in motion</button></div></div><div className="hero-art"><Sculpture/><div className="annotation">WEBSITES<br/>APPS<br/>BRANDS<br/>GROWTH<svg viewBox="0 0 120 70"><path d="M4 61C80 82 25 18 109 12m-13-7 14 7-12 8"/></svg></div><div className="art-caption"><span className="status-dot"/> Independent minds. Shared ambition.<span>EST. 2024</span></div></div></div><div className="hero-bottom"><span>Creative thinking. Real-world impact.</span><a href="#about">Scroll to explore <span>↓</span></a></div></section>
 <section className="trust wrap"><Label>In good company</Label><div className="logos"><span className="kyzo">KÝZO</span><span className="slow">The Slow House</span><span className="hospital"><Cross/> SHIVAKRUPA<small>HOSPITAL</small></span><span className="buy"><Box/> Buy N Build</span><span className="and-more">Good people.<br/>Ambitious brands.</span></div></section>
 <section className="about" id="about"><img className="about-image" src={photos.office} alt="A sunlit creative studio with communal workspaces and plants" loading="lazy"/><div className="about-shade"/><div className="about-content wrap"><div data-reveal><Label>A small team. A big picture.</Label><RevealHeading lines={['Digital solutions.',<>For <em>real</em></>,'businesses.']}/><p>We’re an eight-member creative technology team. Designers, developers and thinkers, working together to build things that make a difference.</p><a className="text-link" href="#why"><span className="round orange"><ArrowUpRight size={19}/></span>Meet your next creative partner</a></div><div className="studio-note">INDEPENDENT STUDIO.<br/>COLLECTIVE AMBITION.</div><div className="stats">{[[8,'','Team members'],[10,'+','Projects delivered'],[100,'%','Client focused'],[0,'∞','Bigger goals']].map(([n,s,l])=><div key={l}><strong>{n!==0&&<span data-count={n}>{n}</span>}{s}</strong><span>{l}</span></div>)}</div></div></section>
 <section className="services wrap section" id="services"><div className="section-top" data-reveal><div><Label>What we do</Label><RevealHeading lines={['End-to-end.','Without the loose ends.']}/><p>From the first sketch to your next milestone. We’re all in.</p></div><a className="subtle-link" href="#capabilities">Explore our capabilities <ArrowUpRight size={17}/></a></div><div className="service-grid">{services.map((s,i)=><button className={`service-card ${service===i?'active':''}`} key={s.title} aria-expanded={service===i} aria-controls="service-detail" onClick={()=>setService(service===i?null:i)}><span className="service-number">0{i+1}</span><s.icon size={29} strokeWidth={1.2}/><h3>{s.title}</h3><p>{s.copy}</p><span className="round">{service===i?<Minus size={16}/>:<ArrowUpRight size={16}/>}</span></button>)}</div><AnimatePresence>{service!==null&&<motion.div id="service-detail" className="service-detail" initial={{opacity:0,y:reduce?0:-8}} animate={{opacity:1,y:0}} exit={{opacity:0}}><p>{services[service].details}</p><a href="#contact">Let’s build it together <ArrowUpRight size={16}/></a></motion.div>}</AnimatePresence></section>
 <section className="work section" id="work">
  <div className="section-top wrap"><div><Label>Selected work</Label><RevealHeading lines={['Real projects.','Lasting impressions.']}/></div><p className="work-note">Different industries. Same attention to detail.<br/><span>Concept previews · project screenshots coming soon.</span></p></div>
  <div className="portfolio-track">{projects.map((p,i)=><article key={p.name} className="project-card">
   <div className="project-index" aria-hidden="true">0{i+1}</div>
   <button className="project-open" aria-label={`View ${p.name} case study`} onFocus={e=>{if(reduce)return;const pin=ScrollTrigger.getById('portfolio');if(pin && e.currentTarget.matches(':focus-visible')){const card=e.currentTarget.closest<HTMLElement>('.project-card')!;const track=card.parentElement!;const offset=Math.min(card.offsetLeft-parseFloat(getComputedStyle(track).paddingLeft),track.scrollWidth-track.clientWidth);window.scrollTo({top:pin.start+offset,behavior:'instant'});pin.getTween()?.progress(1);ScrollTrigger.update()}}} onClick={()=>setSelected(i)}>
    <div className={`project-image ${p.theme}`}><div className="project-image-inner"><img src={p.image} alt={`${p.name} concept preview — ${p.category}`} loading="lazy"/><div className="project-mock-nav"><b>{p.name}</b><span>About &nbsp; Discover &nbsp; Contact <ArrowUpRight size={12}/></span></div><div className="mock-title">{p.headline.split('\n').map(x=><span key={x}>{x}<br/></span>)}</div><span className="mock-button">Discover the experience <ArrowUpRight size={12}/></span></div><span className="project-preview-label">Concept preview</span></div>
    <span className="project-view">View Case Study <ArrowUpRight size={19}/></span>
   </button>
   <div className="project-meta"><div className="project-identity"><h3>{p.name}</h3><p>{p.category}</p></div><div className="project-deliverables"><span>Concept scope</span><p>{p.tags}<br/>Design / Development</p></div><div className="project-description"><span>Overview</span><p>{p.description}</p></div><div className="project-year"><span>Year</span><p>To be confirmed</p></div></div>
  </article>)}</div>
  <div className="work-bottom wrap"><span>Four perspectives. One standard of craft.</span><div className="work-progress"><div className="work-progress-fill"/></div><span>SCROLL TO EXPLORE <ArrowRight size={16}/></span></div>
 </section>
 <section className="process section" id="process"><div className="wrap process-grid"><div data-reveal><Label>How we get there</Label><h2>Simple.<br/>Transparent.<br/>Effective.</h2></div><div className="timeline"><div className="timeline-line"><div className="timeline-fill"/></div>{[['Discover','Understand your goals, your audience and the opportunity.'],['Plan','Define the strategy, the structure and the way forward.'],['Build','Design with intent. Develop with care. Refine together.'],['Grow','Launch is the beginning. Optimize, evolve and scale.']].map(([t,d],i)=><div className="stage" key={t}><span className="stage-node">0{i+1}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
 <section className="capabilities wrap section" id="capabilities"><div className="section-top" data-reveal><div><Label>The bigger toolkit</Label><RevealHeading lines={['More than a website.','A connected system.']}/></div><p>Development is only one piece of the system.<br/>We bring the rest together.</p></div><CapabilitySystem/></section>
 <section className="why section" id="why"><div className="wrap"><div className="section-top" data-reveal><div><Label>Why Tanvo</Label><RevealHeading lines={['More than','just a dev agency.']}/></div><p className="handwritten">A partner in<br/>your growth.<svg viewBox="0 0 160 80" aria-hidden="true"><path d="M140 8C130 65 65 6 16 58m4-18-5 19 21-3"/></svg></p></div><div className="why-grid"><div className="why-image"><img src={photos.desk} alt="A thoughtfully arranged creative workspace" loading="lazy"/><div>Good ideas.<br/>Great people.<br/><em>Better together.</em></div></div><div className="why-reasons"><p>We connect creativity, technology and marketing to help you stand out, earn trust and grow with purpose.</p>{[['Creative + technical','The imagination to see what’s possible. The expertise to make it work.'],['Outcomes over output','Every decision starts with what matters to your business.'],['Your team, extended','Direct conversations. Honest feedback. No layers between us.'],['Here for the long run','From first launch to what’s next, we keep moving with you.']].map(([t,d],i)=><div className="reason" key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{d}</p></div><Plus size={16}/></div>)}</div></div></div></section>
 <section className="insights wrap section" id="insights">
  <div className="perspective-heading"><Label>Notes from the studio</Label><h2>A little<br/>perspective.</h2><p>What we believe.<br/>And how we build.</p><ArrowRight size={30}/></div>
  <div className="perspective-statements">{perspectives.map((p,i)=><button className="insight-row" key={p.title} onClick={()=>setInsight(i)}><span className="insight-number">0{i+1} / {p.category}</span><h3>{p.title}<br/><em>{p.accent}</em></h3><span className="insight-read">Read our perspective <ArrowUpRight size={20}/></span></button>)}</div>
 </section>
 <section className="story" aria-labelledby="story-title">
  <h2 id="story-title" className="sr-only">We don't just build websites. We build digital systems. Built to grow.</h2>
  <div className="story-sticky"><span className="story-caption">The bigger picture</span><div className="story-stage" aria-hidden="true">
    <div className="story-statement"><span>We don’t just</span><span>build websites.</span></div>
    <div className="story-statement"><span>We build</span><span><em>digital systems.</em></span></div>
    <div className="story-statement"><span>Built</span><span>to <em>grow.</em></span></div>
  </div><div className="story-rule"><div className="story-rule-fill"/></div><span className="story-footer">From a first impression to a lasting advantage.</span></div>
 </section>
 <section className="contact section" id="contact"><div className="wrap contact-grid"><div data-reveal><Label>Good things start with a conversation</Label><RevealHeading lines={['Got a project',<>in <em>mind?</em></>]}/><p>A website, an app, or your next big leap.<br/>Let’s turn that “what if” into something real.</p><div className="contact-buttons"><Button onClick={openEnquiry}>Start a Project</Button><a className="text-link" href="tel:+919663341218">Book a call <ArrowUpRight size={17}/></a></div></div><div className="contact-art" aria-hidden="true"><div className="orbit"/><div className="contact-device"><div className="phone-mock"><span>Tanvo.</span><div>Ideas.<br/>Build.<br/><em>Brands.</em></div><small>YOUR NEXT CHAPTER STARTS HERE ↗</small></div></div><span className="contact-note">Turning ideas<br/>into reality. ↖</span></div></div></section>
 </main><footer className="wrap"><div className="footer-main"><div><Brand/><p>Digital products.<br/>A better tomorrow.</p><a className="footer-location" href="https://maps.google.com/?q=Hubli+Dharwad" target="_blank" rel="noreferrer"><MapPin size={14}/> Hubli–Dharwad, India <ArrowUpRight size={13}/></a></div><div><h3>Explore</h3>{['Home','About','Services','Work','Contact'].map(x=><a href={`#${x.toLowerCase()}`} key={x}>{x}</a>)}</div><div><h3>What we do</h3>{services.map(x=><a href="#services" key={x.title}>{x.title}</a>)}</div><div><h3>Say hello</h3><a href="mailto:support@tanvo.in"><Mail size={14}/>support@tanvo.in</a><a href="tel:+919663341218"><Phone size={14}/>+91 96633 41218</a><a href="tel:+916362318041"><Phone size={14}/>+91 63623 18041</a><a href="https://www.instagram.com/tanvo.in/" target="_blank" rel="noreferrer"><Instagram size={14}/>Instagram</a><a href="https://www.linkedin.com/company/tanvoin/" target="_blank" rel="noreferrer"><Linkedin size={14}/>LinkedIn</a></div></div><div className="footer-bottom"><span>© 2026 Tanvo. All rights reserved.</span><span className="footer-legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></span><span><span className="orange-text">✳</span> Built with passion in India.</span><a href="#home">Back to top ↑</a></div></footer>
 <dialog data-lenis-prevent ref={dialog} aria-label={selected!==null ? projects[selected].name : showreel ? 'Studio introduction' : enquiry ? 'Start a project' : 'Studio notes'} className="dialog" onCancel={close} onClick={e=>{if(e.target===e.currentTarget)close()}}><button className="dialog-close" onClick={close} aria-label="Close dialog"><X/></button>{selected!==null&&<article><img className="dialog-image" src={projects[selected].image} alt={projects[selected].name}/><div className="dialog-content"><Label>{projects[selected].tags}</Label><h2>{projects[selected].name}</h2><p>{projects[selected].body}</p><p className="disclosure">Portfolio concept preview. Live project links and verified results will be added when available.</p><Button href="mailto:support@tanvo.in">Create something like this</Button></div></article>}{showreel&&<div className="studio-reel"><Label>Tanvo / Studio introduction</Label><Sculpture/><h2>Think boldly.<br/>Build thoughtfully.<br/><em>Make an impact.</em></h2><p>Eight independent minds. Design, engineering and growth under one roof.</p><a className="button" href="#work" onClick={close}>Explore the work <ArrowUpRight size={17}/></a></div>}{enquiry&&<EnquiryForm/>}{insight!==null&&<div className="dialog-content article"><Label>{perspectives[insight].category} / Notes from the studio</Label><h2>{perspectives[insight].title} {perspectives[insight].accent}</h2><p>{perspectives[insight].body}</p></div>}</dialog>
 <div className="custom-cursor" aria-hidden="true"><span>VIEW</span><MoveUpRight size={16}/></div>
 </>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
